<template>
  <overline position="center">
    {{ $t("chats.settings.invites.name") }}
  </overline>
  <v-data-table :items="$chat.editingChat.invites" :headers="headers">
    <template #[`item.id`]="{ item }: any">
      {{ item.id }}
      <v-btn
        icon
        size="x-small"
        @click="
          $functions.copy(`${$app.site.hostnameWithProtocol}/invite/${item.id}`)
        "
      >
        <v-icon>mdi-content-copy</v-icon>
      </v-btn>
    </template>
    <template #[`item.userId`]="{ item }: any">
      <UserAvatar :user="$user.users[item.userId]" size="32" />
      {{ $user.users[item.userId]?.username }}
    </template>
    <template #[`item.expiredAt`]="{ item }: any">
      {{ item.expiredAt ? $date(item.expiredAt).fromNow() : "Never" }}
    </template>
    <template #[`item.rankId`]="{ item }: any">
      {{
        item.rankId
          ? $chat.editingChat.ranks.find((rank) => rank.id === item.rankId)
              ?.name || "Deleted Rank"
          : "None"
      }}
    </template>
    <template #[`item.actions`]="{ item }: any">
      <v-btn icon @click="invalidate(item.id)">
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </template>
  </v-data-table>
  <small>
    {{ $t("chats.settings.invites.message") }}
  </small>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Overline from "@/components/Core/Typography/Overline.vue";
import UserAvatar from "@/components/Users/UserAvatar.vue";
import {
  GetInvitesForChatDocument,
  InvalidateChatInviteDocument
} from "@/gql/graphql";

export default defineComponent({
  name: "ChatSettingsInvites",
  components: { UserAvatar, Overline },
  data() {
    return {
      headers: [
        {
          title: "Invite Key",
          key: "id"
        },
        {
          title: "Generated by",
          key: "userId"
        },
        {
          title: "Expires",
          key: "expiredAt"
        },
        {
          title: "Auto-grants rank",
          key: "rankId"
        },
        {
          title: "Actions",
          key: "actions"
        }
      ]
    };
  },
  mounted() {
    this.getInvites();
  },
  methods: {
    async invalidate(id: string) {
      await this.$apollo.mutate({
        mutation: InvalidateChatInviteDocument,
        variables: {
          input: {
            inviteId: id,
            associationId: this.$chat.editingChat?.association.id
          }
        }
      });
      this.getInvites();
    },
    async getInvites() {
      const {
        data: {
          chat: { invites }
        }
      } = await this.$apollo.query({
        query: GetInvitesForChatDocument,
        fetchPolicy: "network-only",
        variables: {
          input: {
            associationId: this.$chat.editingChat?.association.id
          }
        }
      });
      this.$chat.editingChat.invites = invites;
    }
  }
});
</script>
