<template>
  <overline position="center">
    {{ $t("chats.settings.invites.name") }}
  </overline>
  <v-data-table :items="$chat.editingChat.invites" :headers="headers">
    <template v-slot:item.id="{ item: { raw } }">
      {{ raw.id }}
      <v-btn icon size="x-small">
        <v-icon>mdi-content-copy</v-icon>
      </v-btn>
    </template>
    <template v-slot:item.userId="{ item: { raw } }">
      <UserAvatar :user="$user.users[raw.userId]" size="32"></UserAvatar>
      {{ $user.users[raw.userId]?.username }}
    </template>
    <template v-slot:item.expiredAt="{ item: { raw } }">
      {{ raw.expiredAt ? $date(raw.expiredAt).fromNow() : "Never" }}
    </template>
    <template v-slot:item.rankId="{ item: { raw } }">
      {{
        raw.rankId
          ? $chat.editingChat.ranks.find((rank) => rank.id === raw.rankId)
              ?.name || "Deleted Rank"
          : "None"
      }}
    </template>
    <template v-slot:item.actions="{ item: { raw } }">
      <v-btn icon>
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </template>
  </v-data-table>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Overline from "@/components/Core/Typography/Overline.vue";
import UserAvatar from "@/components/Users/UserAvatar.vue";

export default defineComponent({
  name: "ChatSettingsInvites",
  components: { UserAvatar, Overline },
  data() {
    return {
      headers: [
        {
          title: "Invite Key",
          key: "id"
        },
        {
          title: "Generated by",
          key: "userId"
        },
        {
          title: "Expires",
          key: "expiredAt"
        },
        {
          title: "Auto-grants rank",
          key: "rankId"
        },
        {
          title: "Actions",
          key: "actions"
        }
      ]
    };
  }
});
</script>

<style scoped></style>
