<template>
  <v-alert type="success" v-if="$user.user?.totpEnable" variant="tonal">
    You have 2FA enabled.
  </v-alert>
  <v-alert type="info" v-else variant="tonal">
    Give your account an extra layer of security by enabling 2FA.
  </v-alert>
  <template v-if="$user.user?.totpEnable">
    <v-card-title>Disable 2FA?</v-card-title>
    <v-card-text>
      If you'd like to disable 2FA, you may do so here, your account will be
      more unsafe if you keep 2FA disabled, please ensure your password is
      secure.
    </v-card-text>
    <v-card-text class="my-n4">
      <v-form v-model="valid" @submit.prevent="disable">
        <v-text-field
          type="password"
          v-model="password"
          label="Password"
          :rules="$validation.user.password"
        />
        <v-text-field
          type="number"
          v-model="code"
          label="2FA code"
          :rules="$validation.user.totp"
        />
      </v-form>
    </v-card-text>
    <v-card-actions>
      <v-spacer></v-spacer>
      <v-btn :disabled="!valid" color="red" @click="disable" :loading="loading">
        Disable
      </v-btn>
    </v-card-actions>
  </template>
  <template v-else-if="stage === 0">
    <v-card-title>Enable 2FA</v-card-title>
    <v-card-text>
      If you'd like to enable it, you may do so here. You will need to scan the
      QR code or enter the secret in your desired 2FA application such as Authy
      or Bitwarden (recommended) and enter the code generated by the
      application.
      <br />
      2FA is a great way to add additional security to your TPU account, please
      note that if you lose access to the 2FA application, you won't be able to
      login.
    </v-card-text>
    <v-card-text class="my-n4">
      <v-form v-model="valid" @submit.prevent="enable">
        <v-text-field
          type="password"
          v-model="password"
          label="Password"
          :rules="$validation.user.passwordSettings"
        />
      </v-form>
    </v-card-text>
    <v-card-actions>
      <v-spacer></v-spacer>
      <v-btn
        :disabled="!valid"
        color="green"
        @click="enable"
        :loading="loading"
      >
        Enable
      </v-btn>
    </v-card-actions>
  </template>
  <template v-else-if="stage === 1">
    <v-card-title>Enable 2FA</v-card-title>
    <v-card-text>
      Please scan the QR code or enter the secret into your desired 2FA
      application.
    </v-card-text>
    <QrcodeVue :value="url" :size="250" class="ml-4" />
    <v-card-text>
      Can't scan? Enter the code:
      <code>
        {{ secret }}
      </code>
    </v-card-text>

    <v-card-text class="my-n4">
      <v-form v-model="valid" @submit.prevent="validate">
        <v-text-field
          type="number"
          v-model="code"
          label="2FA code"
          :rules="$validation.user.totp"
        />
      </v-form>
    </v-card-text>
    <v-card-actions>
      <v-spacer></v-spacer>
      <v-btn
        :disabled="!valid"
        color="green"
        @click="validate"
        :loading="loading"
      >
        Confirm & Enable
      </v-btn>
    </v-card-actions>
    <v-card-text>
      <v-img :src="url" />
    </v-card-text>
    <v-card-text>
      <v-text-field
        v-model="secret"
        label="Secret"
        outlined
        readonly
        :rules="$validation.user.totp"
      />
    </v-card-text>
  </template>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import QrcodeVue from "qrcode.vue";

export default defineComponent({
  name: "TwoFactor",
  components: {
    QrcodeVue
  },
  data() {
    return {
      loading: false,
      stage: 0,
      secret: "",
      code: "",
      password: "",
      valid: false,
      url: ""
    };
  },
  methods: {
    async disable() {
      try {
        this.loading = true;
        await this.axios.patch("/user/totp", {
          code: this.code,
          password: this.password,
          action: "disable"
        });
        this.$toast.success("2FA has been disabled.");
        if (this.$user.user) this.$user.user.totpEnable = false;
        this.loading = false;
      } catch {
        this.loading = false;
      }
    },
    async enable() {
      try {
        this.loading = true;
        const { data } = await this.axios.patch("/user/totp", {
          password: this.password,
          action: "enable"
        });
        this.secret = data.secret;
        this.url = data.url;
        this.stage = 1;
        this.loading = false;
      } catch {
        this.loading = false;
      }
    },
    async validate() {
      try {
        this.loading = true;
        await this.axios.patch("/user/totp", {
          code: this.code,
          action: "validate"
        });
        this.$toast.success("2FA has been enabled.");
        if (this.$user.user) this.$user.user.totpEnable = true;
        this.loading = false;
        this.stage = 0;
        this.code = "";
        this.password = "";
      } catch {
        this.loading = false;
      }
    }
  }
});
</script>

<style scoped></style>
