import { h } from "vue";
import type { IconSet, IconAliases, IconProps } from "vuetify";
import {
  RiAddLine,
  RiAlertFill,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiCalendarLine,
  RiCheckboxBlankLine,
  RiCheckboxCircleFill,
  RiCheckboxFill,
  RiCheckboxIndeterminateFill,
  RiCheckLine,
  RiCircleFill,
  RiCloseCircleFill,
  RiCloseLine,
  RiCollapseDiagonal2Line,
  RiContractLeftLine,
  RiContractRightLine,
  RiDeleteBinLine,
  RiExpandDiagonalLine,
  RiExpandUpDownLine,
  RiFileLine,
  RiInformationFill,
  RiLoopRightFill,
  RiMenuLine,
  RiPencilLine,
  RiSearchLine,
  RiSortAsc,
  RiSortDesc,
  RiStarFill,
  RiStarHalfFill,
  RiStarLine,
  RiSubtractLine
} from "@remixicon/vue";

const aliases: IconAliases = {
  collapse: RiCollapseDiagonal2Line,
  complete: RiCheckLine,
  cancel: RiCloseCircleFill,
  close: RiCloseLine,
  delete: RiDeleteBinLine,
  clear: RiCloseCircleFill,
  success: RiCheckboxCircleFill,
  info: RiInformationFill,
  warning: RiAlertFill,
  error: RiCloseCircleFill,
  prev: RiArrowLeftSLine,
  next: RiArrowRightSLine,
  checkboxOn: RiCheckboxFill,
  checkboxOff: RiCheckboxBlankLine,
  checkboxIndeterminate: RiCheckboxIndeterminateFill,
  delimiter: RiCircleFill,
  sort: RiSortAsc,
  expand: RiExpandDiagonalLine,
  menu: RiMenuLine,
  subgroup: RiArrowDownSLine,
  dropdown: RiArrowDownSLine,
  radioOn: RiCheckboxCircleFill,
  radioOff: RiCheckboxBlankLine,
  edit: RiPencilLine,
  ratingEmpty: RiStarLine,
  ratingFull: RiStarFill,
  ratingHalf: RiStarHalfFill,
  loading: RiLoopRightFill,
  first: RiContractLeftLine,
  last: RiContractRightLine,
  unfold: RiExpandUpDownLine,
  file: RiFileLine,
  plus: RiAddLine,
  minus: RiSubtractLine,
  magnify: RiSearchLine,
  sortAsc: RiSortAsc,
  sortDesc: RiSortDesc,
  calendar: RiCalendarLine
};

const remixIcon: IconSet = {
  component: (props: IconProps) => h(props.tag, { class: ["ri", props.icon] })
};

export { aliases, remixIcon };
